FROM node:18-alpine

WORKDIR /app

COPY next-app/package*.json ./
RUN npm ci --production

COPY next-app ./

ENV NODE_ENV=production \
    PORT=3000

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
